== Service-Granularität
=== Szenario

Die Service-Granularität beschreibt den Umfang der Daten die über eine Schnittstelle 
gesendet werden. Dies gilt unabhängig davon, ob man seine Schnittstellen als Service, 
Microservice oder API bezeichnet. Will man hier einigermaßen redundanzfrei bleiben, 
so steht man vor Krümelmosters großen Dilemma: 
Ein großer Keks oder viele Kleine Kekse. 
Schauen wir uns einen "großen Keks" an einem Beispiel aus der Praxis an.

====
Für einen Kunden soll das Kundenmanagement-System an das Abrechnungssystem und das 
neue Kundenportal angebunden werden. Hierfür sollen Schnittstellen entworfen werden, 
um die Daten auszutauschen.
Das Kundenportal enthält Daten zu Kunden und deren Addressen, die Beratungsgepräche und Protokolle sowie die Bestellungen des Kunden. 

.Stark vereinfachtes Datenmodell der Kundendaten.
image::architecture/Customer-data-example.svg[Example for Customer Data,,256]

Der Architekt des Kundenmanagement-Systems hat entscheden, dass eine Schnittstelle ausreichend ist, um einen 
umfassenden Datenaustausch sicherzustellen.
Daher liefert die Schnittstelle alle Daten des Kunden auf einmal. 
Vom Namen über die Adressen bis zu den Bestelungen und Beratungsprotokollen wird alles ausgeliefert.
Ein Aufruf dauert zwischen 5 und 15 Sekunden und liefert 5 - 20 MB Daten.

Das Abrechnungssystem führt einmal in der Woche - immer Nachts um 1 
Uhr - einen Batchlauf aus, um neue Daten abzuholen und in die eigene Datenbank zu speichern.
Dieser Lauf dauert mit der Schnittstelle 3 Stunden. Solange sich die Kundenanzahl nicht signifikant erhöht, 
kann das Abrechnungssystem mit der Schnittstelle arbeiten. 
Die Gefahr künfitger Performanceprobleme zeichnet sich jedoch bereits ab, sollten weitere 
Systeme ebenfalls Nachts Daten synchronisieren.

Das Kundenportal verfügt über keine eigene Datenhaltung.
Es ruft nach der Anmeldung durch den Kunden den Service auf, um den Kunden zu begrüßen und 
seinen Namen anzuzeigen.
In den Unterseiten des Portals kann der Kunde seine Stammdaten verwalten sowie seine offenen Besellungen einsehen.
Die Laufzeit von bis zu 15 Sekunden bis zum Start der Seite ist für das Kundenportal problematisch.

Auch der Jurist des Hauses hat Datenschutzbedenken, wenn jeder Aufrufer die Beratungsprotokolle und Bestellhistorie erhält.
Der Abruf dieser Daten benötigt zusätzlich einige organisatorische Schritte 
unter Einbezieung des Datenschutzbeauftragten.
====

In diesem Beispiel tritt die Bedeutung eines richtigen Daten-Umfanges (Data-Scope) in 
Schnittstellen sehr deutlich zutage.
Während sich den Performanceproblemen über clevere Replikation Herr werden ließe, 
bleiben die Effizienz- und Zugriffsprobleme erhalten.
Ein anderer "Zuschnitt" der Schnittstelle ist hier gefragt. Also brechen wir den Großen Keks in mehrere Teile und schauen uns die neuen Daten der Schnittstellen an.

.Fokusierter Scope auf die Kerndaten des Kunden.
image::architecture/Customer-data-focus-example.svg[Example for only Customer Data,,256]

Die Schnittstelle zum Abrufen der Kundendaten stellt nun eine Möglichkeit zum abrufen der Kerndaten bereit.
Diese hat einen wesentlich verringerten Umfang. Damit verursacht sie weniger last 
im Kundenverwaltungs-System und schont Netzwerk-Ressourcen.
Außerdem werden die Beratungsprotokolle nun in eine separate Schnittstelle ausgelagert 
und dort speziellen Zugriffsrechten unterworfen.

.Scope der Bestelldaten-Schnittstelle
image::architecture/Customer-data-Order-example.svg[Example for Order Data,,256]

Die Schnittselle für die Bestelldaten bleibt jedoch relativ mächtig. 
Diese weiter aufzubrechen ist nicht sinnvoll, da die Daten der Bestellung in den 
meisten Anwendungsfällen als Ganzes benötigt werden.

=== Analyse
SDie passende Granularität des Daten-Scopes bzw. der passende Schnitt von Schnittstellen ist dabei ein wesentlicher 
Faktor für den Erfolg einer Integrations- und Software-Architektur.

Für den Konsumenten des Services ist der Schnitt der Operationen besonders wichtig.
Idealerweise würde der Konsument genau die von ihm zu einem Zeitpunkt benötigten Daten mit einer 
Operation abrufen können. Dann wäre die Schnittstelle für den Konsumenten optimal.
Jedem Konsumenten eine Optimale Schnittstelle anzubieten ist jedoch nicht wirtschaftlich.
Daher ist es notwendig, dass dieselbe Schnittstelle von verschiedenen Konsumenten genutzt wird.

Für den Konsumenten hat dies zwei mögliche Folgen:

. die Operation liefert mehr Daten als benötigt. Das bedeutet Ineffizienz durch unnötig 
geladene Daten und unnötiger Mehraufwand beim Quellsystem.
. die Operation liefert weniger Daten als benötigt. In diesem Fall muss der Konsument 
weitere Aufrufe ausführen um die Daten zusammenzustellen.
Die Zusammenstellung der Datan durch mahrere Aufrue Aufwand für den Konsumenten und verursacht mehr Kommunikationsvorgänge durch viele Aufrufe.

Daher ist der Schnitt von Operationen und Services immer eine Abwägung von Interessen und Anforderungen der Konsumenten. Dabei sind folgende Faktoren zu bedenken:

*	Der geschäftliche *Bedeutung* der Anwendungsfälle der Operationen
-> So sind i.d.R. Services, die direkt vom Kunden genutzt werden, wichtiger als Reporting-Operationen
*	*Häufigkeit* der Durchführung des Operationsaufrufs 
-> Häufig aufgerufene Operationen müssen effizienter sein als Seltene
*	Nicht funktionale Rahmenbedingungen
**	*Performance*-Anforderungen
**	*Sicherheits*-Anforderungen
-> Sensible Daten sollten getrennt von weniger sensiblen Daten über 
separat gesicherte Schnittstellen angeboten werden.

Berücksichtigt man diese Faktoren kann man eine gut begründete Balance zwischen den Anforderungen finden und umschifft einige gewichtige Schwierigkeiten.
Wie man methodisch vorgehen kann, schauen wir uns in einem weiteren Blogbeitrag an.





Außerdem sollten Standardfunktionalitäten vom Serviceanbieter eingefordert werden, 
spezifische Funktionen jedoch zu den Servicenutzern verlagert werden. Dies reduziert die Bedarfsstreuung und erhöht die Standardisierung.


=== Vorgehen beim Operationsschnitt

Zunächst sollten die Anwendungsfälle der Servicenutzer betrachtet werden, um Gemeinsamkeiten in deren Anforderungen an den Service zu identifizieren. Hierfür betrachtet man die Anwendungsfälle inklusive ihrem Kontext und versucht durch einen veränderten Zuschnitt oder der Verlagerung von Funktionalitäten zwischen verschiedenen Anwendungsfällen, diese zu vereinheitlichen. Ziel dieses Schrittes ist es, die Anzahl der notwendigen Serviceoperatio-nen zu reduzieren.
Danach erfolgt der Abgleich zwischen den Anwendungsfällen und Serviceoperationen, d. h. es wird ermittelt, welche existierenden Operationen welche Anwendungsfälle bereits abde-cken und welche Operationen neu erstellt werden müssen.
Aus funktionaler Sicht ist der Schnitt einer Serviceoperation natürlich am effizientesten, wenn sie exakt die Funktionalität bereitstellt, welche der Servicenutzer benötigt. Geht der Umfang der Operation darüber hinaus, so führt dies zu einer erhöhten Belastung im Bereich der Infra-struktur: 

. des Netzwerkes (z. B. durch der Transport unnötiger Daten)
. der Server (z. B. durch das Ausführen nicht benötigter Funktionalitäten bzw. Laden unnötiger Daten)
. des Clients (z. B. durch das notwendige Ermitteln der Daten aus der Serviceantwort)

Auch eine zu hohe Granularität hat Konsequenzen für die Nutzung des Services. Ist der Leis-tungsumfang zu gering, müssen mehrere Serviceaufrufe durchgeführt werden. Auch dies hat negative Auswirkungen auf die Infrastruktur:
-	des Netzwerkes (z. B. durch unnötig viele Operationsaufrufe)
-	der Server (z. B. durch die Bearbeitung vieler Anfragen)
-	des Clients (z. B. durch die Zusammenführung der Daten)
Da also sowohl Serviceanbieter, als auch Servicenutzer negativ von einem schlechten Ser-viceschnitt betroffen sind, ist es in beider Interesse, Serviceoperation möglichst bedarfsorien-tiert zu schneiden.
Das Problem beim exakten Zuschneiden von Serviceoperationen auf die Anforderungen sind die meist heterogenen Bedürfnisse der unterschiedlichen Servicenutzer. Die Anzahl der not-wendigen Operationen treibt den Entwicklungs- und Wartungsaufwand sehr schnell in nicht gewünschte Höhen. Außerdem würden folgende zentralen Ziele einer SOA verletzt werden:
-	Wartbarkeit
-	Durchgängigkeit
-	Wiederverwendung
-	Standardisierung
Abhängig von der Anzahl und Heterogenität der Anwendungsfälle kann es notwendig sein, diese durch bewusst zu groß oder zu klein geschnittene Operationen zu erfüllen. Bei häufig genutzten oder zeitkritischen Anwendungsfällen bzw. Serviceoperationen ist es dagegen sinnvoll, auf eine höhere Passgenauigkeit zu achten. Letztlich lautet die Zielsetzung, eine gute Balance zwischen Passgenauigkeit und den genannten Zielen zu erreichen.

==== Beispiel eines Operationsschnittes

Das Beispiel in Abbildung 2 stellt vier Anwendungsfälle einer Anwendung dar: Es dient der Erstellung von Verträgen und Rechnungen, außerdem können Angebote versendet und Sup-port geleistet werden.
  
Abbildung 2: Anforderungen der Servicenutzer
Auf der horizontalen Achse sind unterschiedliche Kundendaten angebracht, die Position und Länge der darüber liegenden Anwendungsfälle geben an, ob diese die Kundendaten benöti-gen. Die vertikale Achse stellt die Nutzungshäufigkeit der Anwendungsfälle dar. So gehört der Support zum Tagesgeschäft, während nur selten neue Verträge abgeschlossen werden.
Die Abbildung 3 stellt einen möglichen Serviceschnitt für das beschriebene Beispiel dar. Auf-grund der häufigen Nutzung wurde für den Support-Anwendungsfall eine speziell zugeschnit-tene Operation bereitgestellt. Für das Versenden eines Angebotes müssen hingegen zwei Serviceoperationen aufgerufen werden, um die notwendigen Daten zu erhalten. Für die Rechnungs- und Vertragserstellung sind dagegen drei Operationsaufrufe erforderlich. Zudem liefert der gewählte Operationsschnitt für den Anwendungsfall „Rechnung erstellen“ unnötige Daten. Dies wird jedoch für den selten genutzten Anwendungsfall bewusst in Kauf genom-men.
 
Abbildung 3: Möglicher Operationsschnitt zu den Beispielanforderungen
