= Camunda - Handbuch

TIP: Die Camunda Doku findet sich hier: -> https://docs.camunda.org/manual/7.11/user-guide/

== Konzepte (Camunda)

=== Architektur (Camunda)

== Installation und Einrichtung (Camunda)
=== Deployment Modelle (Camunda)

==== Prozessengine in der Applikation (Camunda)

Bei dieser Methode wird die Prozess-Engine als Dependency in das war-File der Prozessandendung mit hinencompiliert.

.Camunda Engine innerhalb einer Anwendung.war
image::camunda/inAppEngine.svg[Camunda Engine innerhalb einer Anwendung.war,300,opts=inline]

.Maven Scope compile
[source,xml]
----
<dependency>
 	...
	<scope>compile</scope>
</dependency>
----
==== Prozessengine in der Laufzeitumgebung (Camunda)
Bei dieser Methode wird die Prozess-Engine als auf dem JavaEE-Server zentral als dependency bereitgestellt.

.Camunda Engine innerhalb eines JavaEE-Servers
image::camunda/inServerEngine.svg[Camunda Engine innerhalb eines JavaEE-Servers,300,opts=inline]

.Maven Scope provide
[source,xml]
----
<dependency>
 	...
	<scope>provide</scope>
</dependency>
----
==== Prozessengine als eigener Server (Camunda)
==== Geclusterte Prozessengine-Server (Camunda)
==== Mehrmandentenbetireb (Camunda)

== Benutzung (Camunda)
=== Einrichtung der Engine im Projekt (Camunda)
Bootstraping der Engine.
[source,java]
----
include::code/CamundaConfig.java[lines=15..20]
----
Verwendung der Eingine
Prozessstart:
[source,java]
----
include::code/CamundaConfig.java[lines=22..28]
----


=== Dateihandling (Camunda)

==== Datei Download (Camunda)
Die Einbettung von Dokumenten erfolgt über eine Prozessvariable und das Property _cam-file-download_
[source,html]
----
<a cam-file-download="myDownloadFile">Dateiname</a>
----

Die variable muss zuvor wie folgt gefüllt werden.
[source,java]
----
byte[] content = Camunda_Dokumentenspeicher.doc1.toString().getBytes("UTF-8");
FileValue fileContent = Variables.fileValue("Bestelliste.csv").file(content).mimeType("text/csv").encoding("UTF-8").create();
retrieve.setVariable("myDownloadFile", fileContent);
----

==== Datei Upload (Camunda)

[source,html]
----
<input type="file"
       cam-variable-name="INVOICE_DOCUMENT"
       cam-variable-type="File"
       cam-max-filesize="10000000" />
----

=== Fehlerhandling (Camunda)
==== Einführung
Grundsätzlich sollten technische Fehler nicht im Prozess, sondern im Code behandelt werden. 
Fehlerbehandlung im Prozess ist die Ausnahme, wenn auf einen technischen Fehler fachlich 
reagiert werden soll.

Grund:: der Prozess sollte fachlich lesbar bleiben und nicht mit technischen Details 
überfrachtet werden.

==== Retry (Camunda)

Um einen Service im Retry-Modus aufzurufen, muss er im Camunda-Modeller auf Asyncronous gestellt werden. 
Anschließend kann der Retry-Cycle nach https://de.wikipedia.org/wiki/ISO_8601[ISO-8601] definiert werden.

=== Zeitgesteuerte Prozesse (Camunda)
Das Timer-Start-Event muss asyncBefore auf true gesetzt werden.

[source,xml]
----
<bpmn:startEvent id="TimerStartEvent_6Uhr" name="Immer um 6 Uhr" camunda:asyncBefore="true">
  ...
  <bpmn:timerEventDefinition>
    <bpmn:timeCycle xsi:type="bpmn:tFormalExpression">0 0 6 * * ?</bpmn:timeCycle>
  </bpmn:timerEventDefinition>
</bpmn:startEvent>
----

Zusätzlich muss der JobExecutor aktiviert sein.
[source,xml]
----
<process-archive>
	...
	<properties>
		...
		<property name="jobExecutorActivate">true</property>
	</properties>
</process-archive>
----

== Konfiguration (Camunda)

=== History (Camunda)

die Aufbewahrungsdauer wird als Custom-Attribute am Prozess gepflegt.

[source,xml]
----
<process id="oneTaskProcess" name="The One Task Process" isExecutable="true" camunda:historyTimeToLive="P5D">
----

Das Loglevel muss in der processes.xml angegben werden.
[source,xml]
----
<property name="history">audit</property>
----
Folgende Loglevel existieren:

NONE:: Es werden keine Historienereignisse geloggt.

ACTIVITY:: Veränderungen an folgenden Entitäten werden historisiert. Prozess-Instanzen, 
Case-Instanzen, Activity-Instanzen, Case-Activity-Instanzen, Tast-Instanten

AUDIT:: Zusätzlich zu Activity werden noch veränderungen an Variablen.

FULL:: Zusätzlich zum level AUDIT werden veränderungen an folgenden Entitäten erfasst: Formular-Properties, Benutzerinteraktionen, 
Incidents, Logs zu den gelaufenen Jobs, Decision Instance (EVALUATE), Batch (Start, Ende), Identity links, Historic External Task

AUTO:: Das Deployment verwendet die Parameter der anderen Instanzen auf dem Server.