apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: viewer-svc-deployment
spec:
  replicas: 2
  minReadySeconds: 15
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: viewer-svc
    spec:
      containers:
        - image: gcr.io/{PROJECT_ID}/viewer-svc
          imagePullPolicy: Always
          name: viewer-svc
          ports:
            - containerPort: 80
          envFrom:
            - secretRef:
                name: viewer-svc-secrets

-------------------------------------------------------------

apiVersion: v1
kind: Service
metadata:
  name: viewer-service
spec:
  type: LoadBalancer
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: viewer-svc